# -*- coding: utf-8 -*-
"""Ibrohimov Nusratbek

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127j-gNafWjlQSqdN_acQsrsWk9BRGz5n
"""

import numpy as np

math = [1, 2, 3, 4, 5]
math_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

sum_math = np.sum(math)
mean_math = np.mean(math)
product_math = np.prod(math)

print("Massiv: ", math)
print("2D Massiv:\n", math_2d)
print("Massivlar yig'indisi: ", sum_math)
print("O'rtacha: ", mean_math)
print("Ko'paytma: ", product_math)

import pandas as pd

data = {
    'Ism': ['Ali', 'Vali', 'Hasan','Husan','Olim','Jahongir','Firdavs','Ozodbek','Sohibjon','Jonibek'],
    'Yoshi': [31, 41, 42, 23, 34, 19, 18, 20, 17, 21],
    'Shahar': ['Toshkent','Samarqand','Buxoro','Namangan','Guliston','Fergana','Kakand','Andijon','Fergana','Shohimardon']

}

df = pd.DataFrame(data)

print(df)

young_people = df[df['Yoshi'] < 30]
print("30 yoshdan kichiklar:\n", young_people)

df['Yoshi'] += 1
print("Yangilangan DaraFrame:n", df)

Shahar_Fergana = df [df['Shahar'] == 'Fergana']
print("Farg'ona shahridagi odamlar:\n", Shahar_Fergana)